name: Run value to update peg,last price

on:
  schedule:
    # 周一到周五，休斯顿时间 8:00 AM
    - cron: '0 13 * * 1-5'  # 当休斯顿是 CDT (UTC-5) 时，对应当地 8 AM
    - cron: '0 14 * * 1-5'  # 当休斯顿是 CST (UTC-6) 时，对应当地 8 AM

    # 周一到周五，休斯顿时间 11:00 AM
    - cron: '0 16 * * 1-5'  # 当休斯顿是 CDT (UTC-5) 时，对应当地 11 AM
    - cron: '0 17 * * 1-5'  # 当休斯顿是 CST (UTC-6) 时，对应当地 11 AM

    # 周一到周五，休斯顿时间 2:00 PM (14:00)
    - cron: '0 19 * * 1-5'  # 当休斯顿是 CDT (UTC-5) 时，对应当地 2 PM
    - cron: '0 20 * * 1-5'  # 当休斯顿是 CST (UTC-6) 时，对应当地 2 PM

    # 周一到周五，休斯顿时间 3:00 PM (15:00)
    - cron: '0 20 * * 1-5'  # 当休斯顿是 CDT (UTC-5) 时，对应当地 3 PM
    - cron: '0 21 * * 1-5'  # 当休斯顿是 CST (UTC-6) 时，对应当地 3 PM
  workflow_dispatch: # This enables the manual trigger
jobs:
  run-price-update-plandb: # Renamed job for clarity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: List files in workspace
        run: ls -lR # -R for recursive listing, useful if it might be in a subdir
      - name: Run Python script      
        run: python -m papermill value.ipynb valueexe.ipynb

      - name: Upload plandb to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ssh.oregon.render.com
          username: srv-d0h58u0dl3ps73ciqh40  # Your Render SSH username
          key: ${{ secrets.RENDER_SSH_KEY }} # Private key stored in GitHub Secrets
          port: 22
          source: "plan.db" 
          target: "/pv/"                    # Target path on Render server      
