name: Run market breath and scp to render server

on:
  schedule:
    - cron: '0 7 * * *'  # 每天 UTC 中午 12 点运行（可按需修改） (Runs daily at 12 PM UTC, can be modified as needed)
  push:
    paths:
      - 'breath.ipynb'  # 只有当该文件被修改时才触发
    branches:
      - main
  workflow_dispatch: # This enables the manual trigger
jobs:
  run-script-and-upload-csv: # Renamed job for clarity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script      
        run: python -m papermill breath.ipynb breathexe.ipynb

      - name: Upload pkl to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ssh.oregon.render.com
          username: srv-d0h58u0dl3ps73ciqh40  # Your Render SSH username
          key: ${{ secrets.RENDER_SSH_KEY }} # Private key stored in GitHub Secrets
          port: 22
          #source: "marketBreath-3Y.png" #market_breadth_series.pkl" 
          source: "market_breadth_series.pkl" 
          target: "/pv/"                    # Target path on Render server
      - name: Upload png to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ssh.oregon.render.com
          username: srv-d0h58u0dl3ps73ciqh40  # Your Render SSH username
          key: ${{ secrets.RENDER_SSH_KEY }} # Private key stored in GitHub Secrets
          port: 22
          source: "marketBreath-3Y.png" #market_breadth_series.pkl" 
          #source: "market_breadth_series.pkl" 
          target: "/pv/"                    # Target path on Render server
