name: Run Python Script
on:
   schedule:
     - cron: '0 12 * * *'
   push:
      branchese"
         - main:
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # change if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python ./breath.py
      - name: scp image to render server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RENDER_SSH_KEY }}
        run:           
          scp output.png ${{ secrets.RENDER_SSH_KEY }}@ssh.oregon.render.com:/pv/output.png
