name: Run Python Script and Upload

on:
  schedule:
    - cron: '0 12 * * *'  # 每天 UTC 中午 12 点运行（可按需修改）
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python ./code/breath.py

      - name: Upload output.png to Render via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ssh.oregon.render.com
          username: srv-d0h58u0dl3ps73ciqh40  # 用你自己的 Render SSH 用户名
          key: ${{ secrets.RENDER_SSH_KEY }} # 私钥内容保存在 GitHub Secrets 中
          port: 22
          source: "output.png"
          target: "/pv/output.png"
